name: thamarat
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  dio: ^5.4.1
  shared_preferences: ^2.2.2
  get_it: ^7.6.7
  dartz: ^0.10.1
  flutter_secure_storage: ^9.0.0
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/leaves_bg.png
    - assets/vegetables.png
    - assets/truck.png
    - assets/user.jpg
    - assets/vendor.png
    - assets/leave.png

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
          weight: 700
